services:
 nginx:
  image:
   nginx:current
  ports:
   - 443:44
  volumes:
   - wp_data:/var/www
  env_file:
   - var.env
 mariadb:
  ports:
   - 3306:3306
  image:
   mariadb:current
  volumes:
   - db_data:/var/lib/
  networks:
   - inception_network
  env_file:
   - var.env
 wordpress:
  image:
   wordpress:current
  volumes:
   - wp_data:/var/www
  networks:
   - inception_network
  env_file:
   - var.env

volumes:
 wp_data:
  driver:   local
  name :   wp_data
 db_data:
  driver:   local
  name :   db_data

networks:
 inception_network:
  driver: bridge
  name: inception_network
