services:
 mariadb:
  image: mariadb:current
  container_name: mariadb
  build: ./requirements/mariadb
  restart: always
  expose:
   - 3306
  volumes:
   - db_data:/var/lib/
  networks:
   - inception_network
  env_file: .env
 wordpress:
  image: wordpress:current
  container_name: wordpress
  build: ./requirements/wordpress
  restart: always
  expose:
   - 9000
  depends_on:
   - mariadb
  volumes:
   - wp_data:/var/www/wordpress
  networks:
   - inception_network
  env_file: .env
  environment:
   WP_DB : ${WP_DB}
   DB_USR : ${DB_USR}
   DB_PSWD : ${DB_PSWD}
   DB_HOST : ${DB_HOST}
 nginx:
  image: nginx:current
  container_name: nginx
  build: ./requirements/nginx
  restart: always
  depends_on:
   - wordpress
  ports:
   - 443:443
  volumes:
   - wp_data:/var/www/wordpress:ro
  env_file: .env
  networks:
   - inception_network

volumes:
 wp_data:
  driver:   local
  driver_opts :
   type : none
   device : /home/ncrombez/data/wordpress
   o: bind
  name :   wp_data
 db_data:
  driver:   local
  driver_opts :
   type : none
   device : /home/ncrombez/data/db
   o: bind
  name :   db_data

networks:
 inception_network:
  driver: bridge
  name: inception_network
