services:
	nginx:
		image:
			nginx:mainline
		ports:
			443:44
		volumes:
			wp_data
		env_file:"var.env"
	mariadb:
		ports:
			3306:3306
		image:
			mariadb:mainline
		volumes:
			db_data
		network:
			inception_network
		env_file:"var.env"
	wordpress:
		image:
			wordpress:mainline
		volumes:
			wp_data
		network:
			inception_network
		env_file:"var.env"

volumes:
	wp_data:
		driver: 		local
		name	:			wp_data
		mountpoint:	/var/www/
	db_data:
		driver: 		local
		name	:			wp_data
		mountpoint:	/var/data


networks:
	inception_network:
		driver: bridge
		name: inception_network
