FROM alpine:latest

# Install mariadb and dependencies
RUN apk add --no-cache mariadb mariadb-client openrc

# Set up MariaDB data directory

RUN mkdir -p /var/mysqld && chown mysql:mysql /var/mysqld && chmod -R 755 /var/mysqld
RUN mkdir -p /etc/mysql && chown mysql:mysql /etc/mysql && chmod -R 777 /etc/mysql
COPY entrypoint.sh scripts/entrypoint.sh
COPY my.cnf /etc/mysql/my.cnf

RUN chmod 775 scripts/entrypoint.sh

EXPOSE 3306

# Set root password via env var
ENV MYSQL_ROOT_PASSWORD=root

RUN mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql


ENTRYPOINT ["scripts/entrypoint.sh"]