FROM alpine:latest

# Install mariadb and dependencies
RUN apk add --no-cache mariadb mariadb-client

# Set up MariaDB data directory

RUN mkdir -p /run/mysqld && chown mysql:mysql /run/mysqld && chmod -R 755 /run/mysqld
COPY entrypoint.sh scripts/entrypoint.sh

RUN chmod 775 scripts/entrypoint.sh

EXPOSE 3306

# Set root password via env var
ENV MYSQL_ROOT_PASSWORD=root

RUN mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql


ENTRYPOINT ["scripts/entrypoint.sh"]