FROM alpine:3.14


RUN	mkdir -p /var/www/wordpress

#changer l'emplacement de wordrpress ? pitetre ? don't know
#recup le fichier compresser de wordpress, le decompresser et nettoyer le fichier temporaire
RUN apk update &&  apk add mariadb-client \
	php8-mysqli \
	php8-fpm \
	php8-phar \
	php8 \
	php8-phar \
	php8-mbstring \
	php8-json \
	php8-curl \
	php8-mysqli \
	php8-pdo \
	php8-pdo_mysql \
	php8-tokenizer \
	php8-xml \
	php8-ctype \
	php8-iconv \
	php8-openssl \
	php8-session \
	php8-dom \
	php8-simplexml \
	php8-fileinfo \
	php8-gd \
	php8-xmlreader \
	php8-xmlwriter \
	php8-posix \
	curl \
	bash && \
	curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp && \
	ln -s /usr/bin/php8 /usr/bin/php

# rm wordpress.tar.gz


#copie la configuration de wordpress dans le docker en changeant son appartenance pour le donner a www-data
COPY  www.conf /etc/php8/php-fpm.d/www.conf
COPY wp_entry.sh /scripts/wp_entry

RUN chmod -R 755 /scripts
# 	chown -R www-data:www-data /var/www/wordpress && \
# 	mkdir -p /usr/logs/php-fpm && \
# 	mkdir -p /var/www/wordpress && \
# 	chown -R nginx:nginx /var/www/wordpress && \
# 	chown -R nginx:www-data /var/www/wordpress


RUN adduser -D www-data -G www-data && \
	adduser -D nginx -G www-data && \
	mkdir -p /usr/logs/php-fpm && \
	chown -R www-data:www-data /var/www/wordpress && \
	chmod -R 775 /var/www/wordpress


EXPOSE 9000

ENTRYPOINT ["/scripts/wp_entry"]
# CMD ["php-fpm8", "-F"]

