FROM alpine:3.14



#changer l'emplacement de wordrpress ? pitetre ? don't know
#recup le fichier compresser de wordpress, le decompresser et nettoyer le fichier temporaire
RUN apk update &&  apk add curl php8 php8-fpm; \
	curl -o wordpress.tar.gz -fL "https://wordpress.org/wordpress-latest.tar.gz"; \
	tar -xzf wordpress.tar.gz -C /var/www/; \
	rm wordpress.tar.gz


#copie la configuration de wordpress dans le docker en changeant son appartenance pour le donner a www-data
COPY  wp-config.php /var/www/wordpress/ 
# COPY wp_entry.sh /scripts/wp_entry

# RUN chmod -R 755 /scripts && \
# 	chown -R www-data:www-data /var/www/wordpress && \
# 	mkdir -p /usr/logs/php-fpm && \
# 	mkdir -p /var/www/wordpress && \
# 	chown -R nginx:nginx /var/www/wordpress && \
# 	chown -R nginx:www-data /var/www/wordpress


# RUN chmod -R 755 /scripts
RUN adduser -D www-data -G www-data;
RUN	mkdir -p /usr/logs/php-fpm
RUN	mkdir -p /var/www/wordpress
RUN	chown -R www-data:www-data /var/www/wordpress

EXPOSE 9000

# ENTRYPOINT ["/scripts/wp_entry"]
CMD ["php-fpm8", "-F"]

