#Distrib choice
FROM alpine:3.14

#actually specified in the dockerfile or command line. is there more for doc
EXPOSE 443

#update packages manager and add nginx
RUN  apk update && apk add nginx openssl
#copy the nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes \
    -days 365 \
    -keyout /etc/nginx/ssl/inception.key \
    -out /etc/nginx/ssl/inception.crt \
    -subj "/CN=ncrombez.42.fr"

RUN sed -i '/types {/a\    application/javascript  mjs;' /etc/nginx/mime.types


# RUN mkdir /var/www/wordpress
# RUN chmod -R 755 /var/www/wordpress
# RUN chown -R nginx:nginx /var/www/wordpress
# COPY test.html /var/www/wordpress/index.html

#launch nginx : (on debian with "-g deamon off" maybe I need to do the same.. dono)
CMD ["nginx", "-g", "daemon off;"]
# CMD ["service", "nginx", "start"]


#TODO :
#	->handle the nginx user
#	->openssl sertificate is suposed to be here